exports.EmailGenericService = require('./EmailGenericService')
exports.PaymentGenericService = require('./PaymentGenericService')
exports.TaxGenericService = require('./TaxGenericService')
exports.ShippingGenericService = require('./ShippingGenericService')
exports.FulfillmentGenericService = require('./FulfillmentGenericService')
exports.DataStoreGenericService = require('./DataStoreGenericService')
exports.GeolocationGenericService = require('./GeolocationGenericService')
